name: santorini # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Map editor for Battletech MUX
description: |
  Map editor for Battletech MUX

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  santorini_icon.png
title: Santorini

apps:
  santorini:
    command: startapp
  santorini-server:
    command: startserver
parts:
  santorini:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      santorini: build/
      santorini.1: man/man1/

architectures:
  - build-on: amd64

